export interface LinguisticsCard {
  id: number;
  concept: string;
  chapter: string;
  chapterId: number;
  whatIsIt: string;
  whyShouldICare: string;
  nibrasMoment: string;
  memoryHook: string;
  arabicSupport: string;
}

export const allCards: LinguisticsCard[] = [
  // ═══════════════════════════════════════════════════
  // CHAPTER 1: PHONETICS & PHONOLOGY
  // ═══════════════════════════════════════════════════
  {
    id: 1,
    concept: "Phonetics",
    chapter: "Phonetics & Phonology",
    chapterId: 1,
    whatIsIt: "The study of speech sounds — how they are produced, transmitted, and received by the ear.",
    whyShouldICare: "Because pronunciation can completely change meaning. A tiny sound shift can turn one word into another entirely.",
    nibrasMoment: "A student says:\n\"I think it will rain today.\"\n\n…but says 'sink' instead of 'think' 😅\n\nOne sound changed EVERYTHING.",
    memoryHook: "Phonetics = the sounds of language.",
    arabicSupport: "علم الأصوات",
  },
  {
    id: 2,
    concept: "Articulation",
    chapter: "Phonetics & Phonology",
    chapterId: 1,
    whatIsIt: "How we physically produce sounds using the tongue, lips, teeth, and throat.",
    whyShouldICare: "Tiny mouth movements create completely different sounds. Understanding articulation helps you fix persistent pronunciation errors.",
    nibrasMoment: "A student keeps saying:\n\"bery good\"\n\ninstead of:\n\"very good\"\n\nbecause the lips and teeth are not positioned correctly for /v/.",
    memoryHook: "Articulation = how your mouth builds sounds.",
    arabicSupport: "إنتاج الأصوات",
  },
  {
    id: 3,
    concept: "Consonant",
    chapter: "Phonetics & Phonology",
    chapterId: 1,
    whatIsIt: "A speech sound made with blocked or restricted airflow through the vocal tract.",
    whyShouldICare: "Consonants shape words clearly and give English its distinct rhythm. Mispronouncing them can cause confusion.",
    nibrasMoment: "A student says:\n\"cub\" instead of \"cup\"\n\nduring a presentation 😅\n\nThe /b/ and /p/ sounds are easily confused by Arabic speakers because /p/ does not exist in Arabic.",
    memoryHook: "Consonants = sound blockers.",
    arabicSupport: "حرف ساكن",
  },
  {
    id: 4,
    concept: "Vowel",
    chapter: "Phonetics & Phonology",
    chapterId: 1,
    whatIsIt: "A speech sound made with open airflow — the tongue and lips shape the sound but never fully block it.",
    whyShouldICare: "Changing a vowel can completely change meaning. English has more vowel sounds than Arabic, making them tricky for Arabic speakers.",
    nibrasMoment: "A student says:\n\"seat\"\n\nbut mispronounces the vowel and says 'sit' in class 😅\n\n'Take a seat' sounds very different from 'Take a sit.'",
    memoryHook: "Vowels = open sounds.",
    arabicSupport: "حرف متحرك",
  },
  {
    id: 5,
    concept: "Intonation",
    chapter: "Phonetics & Phonology",
    chapterId: 1,
    whatIsIt: "The musical rise and fall of the voice during speech — the melody behind words.",
    whyShouldICare: "The same sentence can sound friendly, angry, or sarcastic depending only on the intonation pattern you use.",
    nibrasMoment: "Your friend says:\n\"Wow… great job.\"\n\nDepending on tone:\n— it may be praise,\n— OR pure sarcasm 😅",
    memoryHook: "Intonation = voice melody.",
    arabicSupport: "نبرة الصوت",
  },
  {
    id: 6,
    concept: "Phonetic Transcription",
    chapter: "Phonetics & Phonology",
    chapterId: 1,
    whatIsIt: "Writing pronunciation using special symbols from the International Phonetic Alphabet (IPA) instead of ordinary spelling.",
    whyShouldICare: "English spelling is chaotic 😅 Phonetic transcription gives you a reliable, scientific way to record exactly how a word sounds.",
    nibrasMoment: "Students ask:\n\"Doctor… why is knife pronounced without the K?!\"",
    memoryHook: "Pronunciation written scientifically.",
    arabicSupport: "الكتابة الصوتية",
  },
  {
    id: 7,
    concept: "Phonology",
    chapter: "Phonetics & Phonology",
    chapterId: 1,
    whatIsIt: "The study of sound systems and patterns in language — how sounds are organized and how they interact with each other.",
    whyShouldICare: "Languages organize sounds differently. A sound combination allowed in Arabic may not work in English, and understanding why prevents errors.",
    nibrasMoment: "An Arabic speaker may struggle with:\n\"street\"\n\nand accidentally say:\n\"istreeet\"\n\nbecause Arabic does not start words with that consonant cluster.",
    memoryHook: "Phonology = sound rules.",
    arabicSupport: "علم أنظمة الأصوات",
  },
  {
    id: 8,
    concept: "Phoneme",
    chapter: "Phonetics & Phonology",
    chapterId: 1,
    whatIsIt: "The smallest unit of sound in a language that can change the meaning of a word.",
    whyShouldICare: "One tiny sound can create a completely different word. Recognising phonemes is essential for clear communication.",
    nibrasMoment: "During IELTS speaking:\n\"bat\"\nvs\n\"pat\"\n\nOne phoneme difference, completely different words.",
    memoryHook: "Tiny sound, huge difference.",
    arabicSupport: "فونيم",
  },
  {
    id: 9,
    concept: "Syllable",
    chapter: "Phonetics & Phonology",
    chapterId: 1,
    whatIsIt: "A beat or sound unit inside a word, typically containing one vowel sound with surrounding consonants.",
    whyShouldICare: "Correct syllable stress improves pronunciation naturally and makes your speech more understandable to native speakers.",
    nibrasMoment: "A student says:\n\"de-VE-lop-ment\"\n\nwith strange stress 😅\n\nThe correct pattern is \"de-VEL-op-ment\".",
    memoryHook: "Syllables = word beats.",
    arabicSupport: "مقطع صوتي",
  },
  // ═══════════════════════════════════════════════════
  // CHAPTER 2: MORPHOLOGY
  // ═══════════════════════════════════════════════════
  {
    id: 10,
    concept: "Morphology",
    chapter: "Morphology",
    chapterId: 2,
    whatIsIt: "The study of how words are built from smaller meaningful units — like breaking words into LEGO pieces.",
    whyShouldICare: "It helps you understand unfamiliar vocabulary by recognising patterns. If you know the parts, you can guess the whole word.",
    nibrasMoment: "A student sees:\n\"unhelpful\"\n\nEven without knowing the word fully:\n— un = not\n— help\n— ful = full of",
    memoryHook: "Morphology = LEGO blocks of language.",
    arabicSupport: "علم بناء الكلمات",
  },
  {
    id: 11,
    concept: "Morpheme",
    chapter: "Morphology",
    chapterId: 2,
    whatIsIt: "The smallest unit of language that carries meaning. It cannot be broken down further without losing its meaning.",
    whyShouldICare: "Words are built from tiny meaningful pieces. Understanding morphemes unlocks thousands of words you have never seen before.",
    nibrasMoment: "WhatsApp message:\n\"re-upload\"\n\nStudents instantly recognise:\n— re = again",
    memoryHook: "Morphemes = tiny meaning units.",
    arabicSupport: "أصغر وحدة تحمل معنى",
  },
  {
    id: 12,
    concept: "Free Morpheme",
    chapter: "Morphology",
    chapterId: 2,
    whatIsIt: "A morpheme that can stand alone as a complete, independent word.",
    whyShouldICare: "Some meaning units are complete words by themselves. These are the foundation of vocabulary building.",
    nibrasMoment: "Words like:\n— book\n— fast\n— coffee\n\ncan stand independently. No attachment needed.",
    memoryHook: "Free morphemes live alone.",
    arabicSupport: "مورفيم حر",
  },
  {
    id: 13,
    concept: "Bound Morpheme",
    chapter: "Morphology",
    chapterId: 2,
    whatIsIt: "A morpheme that must attach to another morpheme — it cannot stand alone as a word.",
    whyShouldICare: "English grammar depends heavily on bound morphemes. Prefixes, suffixes, and inflections are all bound morphemes.",
    nibrasMoment: "Students know:\n\"unhappy\"\n\n…but \"un\" alone means nothing in English.\n\nIt must attach to a word.",
    memoryHook: "Bound morphemes need company.",
    arabicSupport: "مورفيم مقيد",
  },
  {
    id: 14,
    concept: "Prefix",
    chapter: "Morphology",
    chapterId: 2,
    whatIsIt: "A bound morpheme added to the beginning of a word to change its meaning.",
    whyShouldICare: "Prefixes can completely change meaning. Knowing common prefixes like un-, re-, pre-, dis- gives you instant vocabulary power.",
    nibrasMoment: "A student sees:\n\"inactive\"\n\nEven without a dictionary:\n— in = not\n— active",
    memoryHook: "Prefix = before the word.",
    arabicSupport: "سابقة",
  },
  {
    id: 15,
    concept: "Suffix",
    chapter: "Morphology",
    chapterId: 2,
    whatIsIt: "A bound morpheme added to the end of a word to change its grammar or word type.",
    whyShouldICare: "Suffixes often change grammar or word type — turning verbs into nouns, adjectives into adverbs, and more.",
    nibrasMoment: "teach → teacher\n\nThe action becomes a person.\n\nOne suffix changed everything.",
    memoryHook: "Suffix = after the word.",
    arabicSupport: "لاحقة",
  },
  {
    id: 16,
    concept: "Derivation",
    chapter: "Morphology",
    chapterId: 2,
    whatIsIt: "The process of creating a completely new word from an existing one by adding morphemes, often changing the word's category.",
    whyShouldICare: "English creates thousands of words this way. Understanding derivation expands your vocabulary exponentially.",
    nibrasMoment: "motivate\n→ motivation\n→ motivational\n\nOne root, three words, three different uses.",
    memoryHook: "Derivation = word transformation.",
    arabicSupport: "الاشتقاق",
  },
  {
    id: 17,
    concept: "Inflection",
    chapter: "Morphology",
    chapterId: 2,
    whatIsIt: "Changing a word slightly for grammar purposes — like adding -ed for past tense or -s for plural — without creating a new word.",
    whyShouldICare: "English uses inflections constantly. Getting them wrong is one of the most common errors in student writing.",
    nibrasMoment: "A student writes:\n\"Yesterday I walk to university.\"\n\ninstead of:\n\"walked\"",
    memoryHook: "Inflection = grammar adjustment.",
    arabicSupport: "التصريف",
  },
  // ═══════════════════════════════════════════════════
  // CHAPTER 3: SYNTAX
  // ═══════════════════════════════════════════════════
  {
    id: 18,
    concept: "Syntax",
    chapter: "Syntax",
    chapterId: 3,
    whatIsIt: "The rules for arranging words into sentences — the architecture of how words combine to create meaning.",
    whyShouldICare: "Wrong word order sounds unnatural immediately. Even with perfect vocabulary, bad syntax makes communication confusing.",
    nibrasMoment: "\"Very I like mansaf.\" 😅\n\nCorrect:\n\"I really like mansaf.\"\n\nSame words, different order, completely different impression.",
    memoryHook: "Syntax = sentence architecture.",
    arabicSupport: "تركيب الجملة",
  },
  {
    id: 19,
    concept: "Phrase",
    chapter: "Syntax",
    chapterId: 3,
    whatIsIt: "A group of words working together as one unit, but without a subject-verb combination that forms a complete clause.",
    whyShouldICare: "Phrases build larger sentence structures. Recognising them helps you write more complex and natural sentences.",
    nibrasMoment: "— in the library\n— after the lecture\n— very hungry\n\nStudents use phrases constantly without realising they are linguistic units.",
    memoryHook: "Phrase = word team.",
    arabicSupport: "عبارة",
  },
  {
    id: 20,
    concept: "Clause",
    chapter: "Syntax",
    chapterId: 3,
    whatIsIt: "A group of words containing a subject and a verb — the core engine of any sentence.",
    whyShouldICare: "Clauses are the building blocks of sentences. Understanding independent vs dependent clauses prevents run-on sentences and fragments.",
    nibrasMoment: "\"Because I was tired.\"\n\nThe teacher says:\n\"This is incomplete.\"\n\nIt is a dependent clause — it needs a main clause to stand.",
    memoryHook: "Clause = mini sentence engine.",
    arabicSupport: "جملة جزئية",
  },
  {
    id: 21,
    concept: "Deep Structure",
    chapter: "Syntax",
    chapterId: 3,
    whatIsIt: "The underlying, hidden level of sentence meaning — the basic idea before it gets transformed into surface grammar.",
    whyShouldICare: "It explains how two completely different-looking sentences can mean the same thing. This concept reveals that grammar has layers.",
    nibrasMoment: "\"The cat chased the mouse.\"\n\"The mouse was chased by the cat.\"\n\nDifferent surface structures, same deep meaning.\n\nOne active, one passive — but the event is identical.",
    memoryHook: "Deep structure = the real meaning hiding underneath.",
    arabicSupport: "البنية العميقة",
  },
  {
    id: 22,
    concept: "Surface Structure",
    chapter: "Syntax",
    chapterId: 3,
    whatIsIt: "The actual form a sentence takes when spoken or written — the words and word order you see on the page.",
    whyShouldICare: "Different surface structures can express the same deep meaning. Understanding this helps you rewrite sentences for different contexts.",
    nibrasMoment: "A student writes:\n\"I wrote the essay.\"\n\nThe teacher suggests:\n\"The essay was written by me.\"\n\nSame meaning, different surface form.",
    memoryHook: "Surface structure = what you actually say or write.",
    arabicSupport: "البنية السطحية",
  },
  {
    id: 23,
    concept: "Transformation",
    chapter: "Syntax",
    chapterId: 3,
    whatIsIt: "The rules that change a deep structure sentence into different surface structures — like turning active into passive or making a question.",
    whyShouldICare: "Transformations let you express the same idea in many ways. This is crucial for academic writing and professional communication.",
    nibrasMoment: "Active: \"The teacher corrected the homework.\"\n\nPassive: \"The homework was corrected by the teacher.\"\n\nOne transformation, two useful sentence forms.",
    memoryHook: "Transformation = sentence reshaping rules.",
    arabicSupport: "التحويل",
  },
  // ═══════════════════════════════════════════════════
  // CHAPTER 4: SEMANTICS
  // ═══════════════════════════════════════════════════
  {
    id: 24,
    concept: "Semantics",
    chapter: "Semantics",
    chapterId: 4,
    whatIsIt: "The study of meaning in language — how words, phrases, and sentences convey ideas and connect to the real world.",
    whyShouldICare: "Without semantics, words are just empty sounds. Understanding semantics helps you choose the right word for the right situation.",
    nibrasMoment: "A student asks:\n\"What is the difference between 'big' and 'large'?\"\n\nBoth mean the same… but we say 'big brother' and 'large family', not the other way around. Semantics explains why.",
    memoryHook: "Semantics = the study of meaning.",
    arabicSupport: "علم الدلالة",
  },
  {
    id: 25,
    concept: "Lexical Meaning",
    chapter: "Semantics",
    chapterId: 4,
    whatIsIt: "The basic, dictionary meaning of a word — the concept or thing it refers to, independent of context.",
    whyShouldICare: "Lexical meaning is the foundation of vocabulary. It tells you what a word means in its most basic, neutral sense.",
    nibrasMoment: "\"Horse\" = a large four-legged animal.\n\nThat is its lexical meaning. It does not change whether you are in Amman or London.",
    memoryHook: "Lexical meaning = dictionary definition.",
    arabicSupport: "المعنى المعجمي",
  },
  {
    id: 26,
    concept: "Conceptual Meaning",
    chapter: "Semantics",
    chapterId: 4,
    whatIsIt: "The core, objective meaning shared by all speakers of a language — the features that define a word regardless of context.",
    whyShouldICare: "It is the stable part of meaning. While associative meaning can vary, conceptual meaning stays the same for everyone.",
    nibrasMoment: "\"Woman\" conceptually means:\n— human\n— adult\n— female\n\nThese features do not change from Jordan to Canada.",
    memoryHook: "Conceptual meaning = the universal core of a word.",
    arabicSupport: "المعنى المفاهيمي",
  },
  {
    id: 27,
    concept: "Associative Meaning",
    chapter: "Semantics",
    chapterId: 4,
    whatIsIt: "The emotional, cultural, or personal connections a word carries beyond its literal definition.",
    whyShouldICare: "Words carry cultural baggage. The same word can feel warm in one culture and cold in another — this affects how people perceive you.",
    nibrasMoment: "\"Home\" in English has warm, safe associations.\n\nIn Arabic, \"بيت\" (bayt) carries even deeper family and belonging associations.\n\nThe conceptual meaning is the same, but the associative meaning is deeply cultural.",
    memoryHook: "Associative meaning = the feelings a word brings.",
    arabicSupport: "المعنى الترابطي",
  },
  {
    id: 28,
    concept: "Synonymy",
    chapter: "Semantics",
    chapterId: 4,
    whatIsIt: "The relationship between words that have very similar meanings — like 'big' and 'large', or 'happy' and 'joyful'.",
    whyShouldICare: "Using synonyms makes your writing richer and more varied. However, true synonyms are rare — most have subtle differences in use.",
    nibrasMoment: "A student writes:\n\"I bought a cheap car.\"\n\nBut in a formal essay:\n\"I purchased an affordable vehicle.\"\n\nSame idea, better word choice using synonyms.",
    memoryHook: "Synonymy = similar meaning siblings.",
    arabicSupport: "ترادف",
  },
  {
    id: 29,
    concept: "Antonymy",
    chapter: "Semantics",
    chapterId: 4,
    whatIsIt: "The relationship between words with opposite meanings — like 'hot' and 'cold', or 'alive' and 'dead'.",
    whyShouldICare: "Antonyms help define words by contrast. They are powerful tools in writing, especially for creating emphasis and comparison.",
    nibrasMoment: "\"The desert is hot, but the mountains are cold.\"\n\nWithout antonyms, you cannot express contrast effectively.",
    memoryHook: "Antonymy = opposite twins.",
    arabicSupport: "تضاد",
  },
  {
    id: 30,
    concept: "Polysemy",
    chapter: "Semantics",
    chapterId: 4,
    whatIsIt: "When a single word has multiple related meanings — the meanings all connect back to a common origin.",
    whyShouldICare: "English is full of polysemous words. Understanding this prevents confusion and makes you a more flexible communicator.",
    nibrasMoment: "\"Head\" = the body part on your neck.\n\"Head\" = the leader of a company.\n\"Head\" = the top of a mountain.\n\nAll related to 'the top' — that is polysemy.",
    memoryHook: "Polysemy = one word, many connected meanings.",
    arabicSupport: "تعدد المعاني",
  },
  {
    id: 31,
    concept: "Homonymy",
    chapter: "Semantics",
    chapterId: 4,
    whatIsIt: "When two completely different words happen to have the same form — same pronunciation or spelling, but unrelated meanings.",
    whyShouldICare: "Homonyms are everywhere in English and they cause real confusion, especially in listening and reading comprehension.",
    nibrasMoment: "\"Bat\" = the flying animal.\n\"Bat\" = the sports equipment.\n\nCompletely unrelated meanings that share the same form.",
    memoryHook: "Homonymy = accidental twins.",
    arabicSupport: "متشابهات اللفظ",
  },
  {
    id: 32,
    concept: "Metaphor",
    chapter: "Semantics",
    chapterId: 4,
    whatIsIt: "Understanding one thing in terms of another — describing something by saying it IS something else, without using 'like' or 'as'.",
    whyShouldICare: "Metaphors shape how we think, not just how we speak. They appear constantly in academic, professional, and everyday English.",
    nibrasMoment: "\"Time is money.\"\n\"He has a heart of stone.\"\n\"The classroom was a zoo.\"\n\nWe use metaphors every day without noticing.",
    memoryHook: "Metaphor = understanding X through Y.",
    arabicSupport: "استعارة",
  },
  {
    id: 33,
    concept: "Metonymy",
    chapter: "Semantics",
    chapterId: 4,
    whatIsIt: "Using the name of one thing to refer to something closely related to it — substitution based on association rather than similarity.",
    whyShouldICare: "Metonymy is extremely common in news, politics, and daily speech. Recognising it helps you read between the lines.",
    nibrasMoment: "\"The White House announced...\"\n\nThe building did not speak — the government did.\n\nThat is metonymy: the place stands for the institution.",
    memoryHook: "Metonymy = close substitute.",
    arabicSupport: "مجاز مرسل",
  },
  // ═══════════════════════════════════════════════════
  // CHAPTER 5: PRAGMATICS
  // ═══════════════════════════════════════════════════
  {
    id: 34,
    concept: "Pragmatics",
    chapter: "Pragmatics",
    chapterId: 5,
    whatIsIt: "The study of how context contributes to meaning — how people use language in real situations beyond the literal words.",
    whyShouldICare: "Knowing what words mean is not enough. You must know when, where, how, and to whom to say them. That is pragmatics.",
    nibrasMoment: "\"Can you pass the salt?\"\n\nLiterally: a question about ability.\nPragmatically: a polite request.\n\nThe meaning is in the context, not the words.",
    memoryHook: "Pragmatics = meaning in context.",
    arabicSupport: "علم التداول",
  },
  {
    id: 35,
    concept: "Context",
    chapter: "Pragmatics",
    chapterId: 5,
    whatIsIt: "The situation, setting, relationship, and background knowledge that give language its full meaning beyond the literal words.",
    whyShouldICare: "The same sentence can mean completely different things depending on who says it, where, when, and to whom.",
    nibrasMoment: "\"It is cold in here.\"\n\nSaid at home → a simple observation.\nSaid by a guest to a host → a polite request to close the window.\n\nSame words, different context, different meaning.",
    memoryHook: "Context = the stage where meaning performs.",
    arabicSupport: "السياق",
  },
  {
    id: 36,
    concept: "Deixis",
    chapter: "Pragmatics",
    chapterId: 5,
    whatIsIt: "Words that require context to be understood — their meaning depends on who is speaking, where, and when.",
    whyShouldICare: "Deictic words are among the most common in any language, but their meaning shifts every time someone new uses them.",
    nibrasMoment: "\"I am here now.\"\n\nIf Nibras says it in Amman, \"I\" = Nibras, \"here\" = Amman.\nIf Ahmad says it in Irbid, \"I\" = Ahmad, \"here\" = Irbid.\n\nSame words, different reference.",
    memoryHook: "Deixis = context-dependent pointers.",
    arabicSupport: "الإحالة",
  },
  {
    id: 37,
    concept: "Presupposition",
    chapter: "Pragmatics",
    chapterId: 5,
    whatIsIt: "An assumption that a speaker takes for granted when making a statement — something that must be true for the sentence to make sense.",
    whyShouldICare: "Presuppositions reveal hidden assumptions. Understanding them helps you detect bias, persuasion, and hidden meanings in what others say.",
    nibrasMoment: "\"When did you stop procrastinating?\"\n\nThis question presupposes that you DID procrastinate.\n\nWhether you answer or not, the assumption is already planted.",
    memoryHook: "Presupposition = hidden assumption behind the sentence.",
    arabicSupport: "افتراض ضمني",
  },
  {
    id: 38,
    concept: "Implicature",
    chapter: "Pragmatics",
    chapterId: 5,
    whatIsIt: "What a speaker implies or suggests without directly stating it — the meaning you infer beyond the literal words.",
    whyShouldICare: "Much of real communication happens through implicature. Mastering it is what separates intermediate speakers from advanced ones.",
    nibrasMoment: "A student asks:\n\"Is there any labneh left?\"\n\nMother replies:\n\"Your brother came home hungry.\"\n\nShe never said 'no' — but the implicature is clear.",
    memoryHook: "Implicature = reading between the lines.",
    arabicSupport: "تضمين",
  },
  {
    id: 39,
    concept: "Speech Act",
    chapter: "Pragmatics",
    chapterId: 5,
    whatIsIt: "The theory that saying something IS doing something — utterances are actions, not just descriptions of reality.",
    whyShouldICare: "Language is a tool for action. Every time you speak, you are performing an act: promising, requesting, warning, apologising.",
    nibrasMoment: "\"I promise to call you tomorrow.\"\n\nSaying this is not just describing a promise — it IS the act of promising.\n\nThe words create the commitment.",
    memoryHook: "Speech act = words as actions.",
    arabicSupport: "الفعل الكلامي",
  },
  {
    id: 40,
    concept: "Direct Speech Act",
    chapter: "Pragmatics",
    chapterId: 5,
    whatIsIt: "When the form of the sentence directly matches its function — a question is a question, a command is a command.",
    whyShouldICare: "Direct speech acts are clear and efficient. They are the foundation of basic communication, especially in informal situations.",
    nibrasMoment: "\"Sit down.\" → Command (imperative form)\n\"What time is it?\" → Question (interrogative form)\n\nThe form and function match perfectly.",
    memoryHook: "Direct speech act = what you see is what you get.",
    arabicSupport: "فعل كلامي مباشر",
  },
  {
    id: 41,
    concept: "Indirect Speech Act",
    chapter: "Pragmatics",
    chapterId: 5,
    whatIsIt: "When the form of a sentence does not match its intended function — an indirect way of achieving a communicative goal.",
    whyShouldICare: "Most real-world politeness relies on indirect speech acts. They are essential for professional, academic, and social communication.",
    nibrasMoment: "\"Could you help me with this?\"\n\nForm: Question about ability.\nFunction: Request for help.\n\nIndirect because you are not really asking if they CAN — you want them TO.",
    memoryHook: "Indirect speech act = saying one thing, meaning another.",
    arabicSupport: "فعل كلامي غير مباشر",
  },
  // ═══════════════════════════════════════════════════
  // CHAPTER 6: DISCOURSE ANALYSIS
  // ═══════════════════════════════════════════════════
  {
    id: 42,
    concept: "Discourse",
    chapter: "Discourse Analysis",
    chapterId: 6,
    whatIsIt: "Language in use beyond the single sentence — how text and talk are organised into meaningful connected communication.",
    whyShouldICare: "Real language does not come in isolated sentences. Understanding discourse helps you read academic texts, write essays, and follow conversations.",
    nibrasMoment: "A student can understand every word in a lecture but still miss the main point.\n\nWhy? Because understanding individual sentences is not the same as understanding discourse — the connected flow of ideas.",
    memoryHook: "Discourse = language beyond sentences.",
    arabicSupport: "الخطاب",
  },
  {
    id: 43,
    concept: "Cohesion",
    chapter: "Discourse Analysis",
    chapterId: 6,
    whatIsIt: "The grammatical and lexical links that connect sentences to each other — the 'glue' that holds a text together.",
    whyShouldICare: "Without cohesion, writing feels disconnected and confusing. Good cohesion is what examiners look for in IELTS and TOEFL essays.",
    nibrasMoment: "\"Ahmad loves football. He plays it every weekend.\"\n\n\"He\" and \"it\" are cohesive ties — they connect back to Ahmad and football.\n\nWithout them, the text would feel robotic.",
    memoryHook: "Cohesion = the glue of text.",
    arabicSupport: "التماسك النصي",
  },
  {
    id: 44,
    concept: "Coherence",
    chapter: "Discourse Analysis",
    chapterId: 6,
    whatIsIt: "The logical flow and sense-making of a text — whether the ideas connect in a way the reader can follow, even without explicit grammatical links.",
    whyShouldICare: "A text can be grammatically perfect but still confusing. Coherence ensures your reader actually understands your message as a whole.",
    nibrasMoment: "\"It was raining. I opened my umbrella.\"\n\nNo explicit connectors — but perfectly coherent.\n\nThe reader understands the logical relationship between the sentences.",
    memoryHook: "Coherence = the logic of text.",
    arabicSupport: "التكامل النصي",
  },
  {
    id: 45,
    concept: "Turn-taking",
    chapter: "Discourse Analysis",
    chapterId: 6,
    whatIsIt: "The rules and patterns that govern who speaks when in a conversation — the natural rhythm of speakers exchanging turns.",
    whyShouldICare: "Interrupting too much or staying silent too long can make conversations awkward. Understanding turn-taking helps you participate naturally.",
    nibrasMoment: "In a group discussion:\nStudent A finishes speaking → small pause → Student B begins.\n\nThat natural switch is turn-taking in action. Interrupting without signals is considered rude in most cultures.",
    memoryHook: "Turn-taking = conversation traffic rules.",
    arabicSupport: "تبادل الأدوار في الحديث",
  },
  {
    id: 46,
    concept: "Adjacency Pairs",
    chapter: "Discourse Analysis",
    chapterId: 6,
    whatIsIt: "Paired utterances where the first part naturally expects a specific second part — like question-answer or greeting-greeting.",
    whyShouldICare: "Adjacency pairs are the backbone of everyday conversation. Knowing them helps you respond appropriately in social situations.",
    nibrasMoment: "\"How are you?\" → \"Fine, thank you.\"\n\"Good morning!\" → \"Good morning!\"\n\"Thank you!\" → \"You are welcome.\"\n\nDisrupting the pair feels strange.",
    memoryHook: "Adjacency pairs = conversational handshake.",
    arabicSupport: "أزواج المجاورة",
  },
  {
    id: 47,
    concept: "Hedges",
    chapter: "Discourse Analysis",
    chapterId: 6,
    whatIsIt: "Words and phrases that soften a statement, making it less direct or less certain — like 'maybe', 'sort of', 'it seems that'.",
    whyShouldICare: "Hedges are essential for politeness, diplomacy, and academic writing. They show you are not oversimplifying complex ideas.",
    nibrasMoment: "\"This might be the best solution.\"\n\nvs.\n\n\"This IS the best solution.\"\n\nThe first sounds thoughtful. The second sounds aggressive. Hedges matter.",
    memoryHook: "Hedges = softening cushions for language.",
    arabicSupport: "المهملات اللغوية",
  },
  // ═══════════════════════════════════════════════════
  // CHAPTER 7: NEUROLINGUISTICS
  // ═══════════════════════════════════════════════════
  {
    id: 48,
    concept: "Neurolinguistics",
    chapter: "Neurolinguistics",
    chapterId: 7,
    whatIsIt: "The study of how the brain processes, produces, and understands language — where language lives in the mind.",
    whyShouldICare: "Understanding the brain-language connection helps explain why language disorders happen and how language learning actually works physically.",
    nibrasMoment: "When a student learns a new word, millions of neurons fire in specific brain regions.\n\nLanguage is not just a skill — it is a biological process happening inside your skull.",
    memoryHook: "Neurolinguistics = brain meets language.",
    arabicSupport: "علم الأعصاب اللغوي",
  },
  {
    id: 49,
    concept: "Aphasia",
    chapter: "Neurolinguistics",
    chapterId: 7,
    whatIsIt: "A language disorder caused by brain damage — affecting speaking, understanding, reading, or writing, while intelligence remains intact.",
    whyShouldICare: "Aphasia shows that language and general intelligence are separate brain functions. It proves that language has its own dedicated brain areas.",
    nibrasMoment: "After a stroke, a brilliant professor may struggle to say simple words.\n\nTheir intelligence is unchanged, but their language system is damaged.\n\nThat is aphasia.",
    memoryHook: "Aphasia = language loss, not mind loss.",
    arabicSupport: "الحبسة",
  },
  {
    id: 50,
    concept: "Broca's Aphasia",
    chapter: "Neurolinguistics",
    chapterId: 7,
    whatIsIt: "A type of aphasia caused by damage to Broca's area in the brain — patients struggle to produce fluent speech but comprehension remains relatively good.",
    whyShouldICare: "It reveals that speech production and comprehension use different brain areas. Broca's area is specifically for speaking and writing.",
    nibrasMoment: "A patient with Broca's aphasia might say:\n\"Walk… doctor… uh… hospital… day.\"\n\nThey know what they want to say, but cannot form smooth sentences.\n\nUnderstanding is much better than speaking.",
    memoryHook: "Broca's = trouble speaking, understanding OK.",
    arabicSupport: "حبسة بروكا",
  },
  {
    id: 51,
    concept: "Wernicke's Aphasia",
    chapter: "Neurolinguistics",
    chapterId: 7,
    whatIsIt: "A type of aphasia caused by damage to Wernicke's area — patients produce fluent speech but it often lacks meaning, and comprehension is severely impaired.",
    whyShouldICare: "It shows that even fluent speech can be meaningless if the comprehension area is damaged. Wernicke's area is the brain's language understanding centre.",
    nibrasMoment: "A patient with Wernicke's aphasia speaks fluently:\n\"The flim is on the gart and the bingle is…\"\n\nSounds smooth, but makes no sense.\n\nThey also cannot understand what others say to them.",
    memoryHook: "Wernicke's = fluent speech but no comprehension.",
    arabicSupport: "حبسة فيرنيكه",
  },
  {
    id: 52,
    concept: "Slip of the Tongue",
    chapter: "Neurolinguistics",
    chapterId: 7,
    whatIsIt: "An accidental speech error — when the brain's speech production system momentarily glitches, swapping sounds, words, or parts of words.",
    whyShouldICare: "Slips of the tongue are not random — they follow predictable patterns that reveal how the brain plans and organises speech before we say it.",
    nibrasMoment: "A student meant to say:\n\"I need to go to the post office.\"\n\nBut accidentally said:\n\"I need to go to the ghost office.\" 😅\n\nThe brain swapped 'p' and 'gh' — a classic spoonerism.",
    memoryHook: "Slip of the tongue = brain glitch revealing speech planning.",
    arabicSupport: "زللة لسان",
  },
  // ═══════════════════════════════════════════════════
  // CHAPTER 8: LANGUAGE ACQUISITION
  // ═══════════════════════════════════════════════════
  {
    id: 53,
    concept: "Language Acquisition",
    chapter: "Language Acquisition",
    chapterId: 8,
    whatIsIt: "The natural process by which humans learn a language — especially first language learning in childhood, without formal instruction.",
    whyShouldICare: "Understanding how children acquire language helps you understand your own second language learning process and what makes it harder.",
    nibrasMoment: "A Jordanian baby hears Arabic at home and within two years is speaking in sentences.\n\nNo grammar lessons. No textbooks. No exams.\n\nThat is the incredible power of language acquisition.",
    memoryHook: "Language acquisition = natural language learning.",
    arabicSupport: "اكتساب اللغة",
  },
  {
    id: 54,
    concept: "Caregiver Speech",
    chapter: "Language Acquisition",
    chapterId: 8,
    whatIsIt: "The special way adults speak to young children — simplified vocabulary, slower tempo, higher pitch, and lots of repetition.",
    whyShouldICare: "Caregiver speech is not 'baby talk' — it is a carefully tuned linguistic input system that helps children acquire language step by step.",
    nibrasMoment: "A mother says to her toddler:\n\"Look! A kitty! Nice kitty!\"\n\nShort sentences. Clear pronunciation. Repetition.\n\nThis is not random — it is perfectly designed teaching.",
    memoryHook: "Caregiver speech = the child's first classroom.",
    arabicSupport: "خطاب مقدم الرعاية",
  },
  {
    id: 55,
    concept: "Babbling",
    chapter: "Language Acquisition",
    chapterId: 8,
    whatIsIt: "The pre-language stage when babies produce repetitive syllable sequences like 'ba-ba-ba' or 'da-da-da' as practice for real speech.",
    whyShouldICare: "Babbling is not random noise — it is the brain and mouth practising the sounds of language. All babies babble, whether hearing or deaf.",
    nibrasMoment: "A baby in Amman says:\n\"ba-ba-ba-ba\"\n\nThe parents get excited:\n\"She said baba!\"\n\nIt might not mean 'father' yet — but it is a crucial language milestone.",
    memoryHook: "Babbling = speech practice mode.",
    arabicSupport: "المناغاة",
  },
  {
    id: 56,
    concept: "Overgeneralization",
    chapter: "Language Acquisition",
    chapterId: 8,
    whatIsIt: "When language learners apply a grammar rule too broadly — creating forms that follow the rule but are actually incorrect exceptions.",
    whyShouldICare: "Overgeneralization shows that learners are actively thinking about grammar rules, not just memorising. It is a sign of progress, not failure.",
    nibrasMoment: "A child says:\n\"I goed to school.\"\n\nNot because they heard it — but because they learned the '-ed' rule and applied it everywhere.\n\nThe error shows active learning.",
    memoryHook: "Overgeneralization = rule applied too widely.",
    arabicSupport: "الإفراط في التعميم",
  },
  {
    id: 57,
    concept: "Critical Period",
    chapter: "Language Acquisition",
    chapterId: 8,
    whatIsIt: "The biologically determined window (roughly birth to puberty) during which language acquisition happens most naturally and completely.",
    whyShouldICare: "After the critical period, learning a language becomes much harder. This explains why children who move to a new country learn the language faster than adults.",
    nibrasMoment: "A family moves from Jordan to Canada when their child is 5.\n\nWithin a year, the child speaks fluent English.\n\nThe parents, despite studying for years, still struggle with accent and grammar.\n\nThe critical period makes the difference.",
    memoryHook: "Critical period = nature's language learning deadline.",
    arabicSupport: "الفترة الحرجة",
  },
  // ═══════════════════════════════════════════════════
  // CHAPTER 9: SOCIOLINGUISTICS
  // ═══════════════════════════════════════════════════
  {
    id: 58,
    concept: "Sociolinguistics",
    chapter: "Sociolinguistics",
    chapterId: 9,
    whatIsIt: "The study of how society affects language and how language affects society — the relationship between language and social factors.",
    whyShouldICare: "Language is never neutral. Your accent, vocabulary, and grammar choices signal your social identity, education, and background.",
    nibrasMoment: "A student from Irbid and a student from Aqaba meet at the University of Jordan.\n\nThey speak English differently — not because of ability, but because of their social and regional backgrounds.",
    memoryHook: "Sociolinguistics = language meets society.",
    arabicSupport: "علم اللغة الاجتماعي",
  },
  {
    id: 59,
    concept: "Dialect",
    chapter: "Sociolinguistics",
    chapterId: 9,
    whatIsIt: "A variety of a language with its own vocabulary, grammar, and pronunciation — different from the standard form but still the same language.",
    whyShouldICare: "Dialects are not 'broken' versions of a language — they are systematic, rule-governed varieties. Understanding dialect diversity reduces language prejudice.",
    nibrasMoment: "Jordanian Arabic has multiple dialects:\n— Ammani (urban)\n— Baladi (rural)\n— Bedouin\n\nEach has its own grammar and vocabulary.\n\nNone is 'better' — they are all legitimate dialects.",
    memoryHook: "Dialect = a language's family member.",
    arabicSupport: "لهجة",
  },
  {
    id: 60,
    concept: "Accent",
    chapter: "Sociolinguistics",
    chapterId: 9,
    whatIsIt: "A particular way of pronouncing a language — related only to pronunciation, not grammar or vocabulary.",
    whyShouldICare: "Everyone has an accent. The idea of a 'correct' accent is a social myth. Understanding this builds confidence in language learners.",
    nibrasMoment: "A student says:\n\"I want to sound British.\"\n\nBut their Jordanian accent is perfectly valid.\n\nAccents reflect identity, not intelligence or language ability.",
    memoryHook: "Accent = pronunciation fingerprint.",
    arabicSupport: "لكنة",
  },
  {
    id: 61,
    concept: "Bilingualism",
    chapter: "Sociolinguistics",
    chapterId: 9,
    whatIsIt: "The ability to use two languages fluently — switching between them depending on context, topic, and conversation partner.",
    whyShouldICare: "Bilingualism gives cognitive advantages, career opportunities, and cultural bridges. Most Jordanians are naturally bilingual (Arabic + English).",
    nibrasMoment: "A Jordanian student studies engineering in English, texts friends in Arabic, and watches Turkish dramas with Arabic subtitles.\n\nThat is real-world bilingualism — and it is a superpower.",
    memoryHook: "Bilingualism = two language superpowers.",
    arabicSupport: "ثنائية اللغة",
  },
  {
    id: 62,
    concept: "Code-switching",
    chapter: "Sociolinguistics",
    chapterId: 9,
    whatIsIt: "The practice of alternating between two or more languages or dialects within a single conversation — or even a single sentence.",
    whyShouldICare: "Code-switching is not a sign of poor language skills. It is a sophisticated communicative strategy used by bilinguals worldwide.",
    nibrasMoment: "\"Ana ba7eb the new Marvel movie, kano really impressive.\"\n\nMixing Arabic and English in one sentence is not 'broken' language — it is skilled code-switching used by millions of bilinguals daily.",
    memoryHook: "Code-switching = language dance between worlds.",
    arabicSupport: "تبديل الكود",
  },
  {
    id: 63,
    concept: "Register",
    chapter: "Sociolinguistics",
    chapterId: 9,
    whatIsIt: "The level of formality in language use — from very formal (academic writing) to very informal (texting friends).",
    whyShouldICare: "Using the wrong register can damage relationships or miss job opportunities. Choosing the right register is a key professional skill.",
    nibrasMoment: "Same person, different registers:\n\nTo a professor: \"I would appreciate your guidance regarding my research.\"\nTo a friend: \"Yo, can you check my essay real quick?\"\n\nSame need, completely different language.",
    memoryHook: "Register = the right language for the right occasion.",
    arabicSupport: "مستوى اللغة",
  },
  {
    id: 64,
    concept: "Prestige",
    chapter: "Sociolinguistics",
    chapterId: 9,
    whatIsIt: "The social value attached to a particular language variety, dialect, or accent — some forms are considered 'better' by society regardless of linguistic facts.",
    whyShouldICare: "Prestige influences how people judge you based on your speech. Understanding it helps you navigate social expectations without losing your identity.",
    nibrasMoment: "In many Arab countries, speaking with a 'Khaleeji' or 'American' accent is often associated with higher social prestige.\n\nBut this is a social attitude, not a linguistic fact.\n\nLinguistically, all accents are equal.",
    memoryHook: "Prestige = the social badge of a language variety.",
    arabicSupport: "الهيبة اللغوية",
  },
  {
    id: 65,
    concept: "Style-shifting",
    chapter: "Sociolinguistics",
    chapterId: 9,
    whatIsIt: "When a speaker changes their language style — accent, vocabulary, or grammar — depending on who they are talking to.",
    whyShouldICare: "Everyone style-shifts. It is a natural, unconscious behaviour that helps us connect with different people in different contexts.",
    nibrasMoment: "The way you speak to your grandmother is different from the way you speak to your classmates.\n\nNeither is your 'real' way of speaking — both are real.\n\nThat is style-shifting.",
    memoryHook: "Style-shifting = social chameleon in language.",
    arabicSupport: "تبديل الأسلوب",
  },
  {
    id: 66,
    concept: "Linguistic Relativity",
    chapter: "Sociolinguistics",
    chapterId: 9,
    whatIsIt: "The idea that the language you speak influences how you think and perceive the world — also known as the Sapir-Whorf Hypothesis.",
    whyShouldICare: "If true, learning a new language literally changes how you see reality. Different languages divide the world differently.",
    nibrasMoment: "Arabic has one word for 'uncle' — 'ammo' (paternal) and 'khal' (maternal).\n\nEnglish just says 'uncle'.\n\nDoes Arabic make family relationships more specific in the speaker's mind? That is linguistic relativity.",
    memoryHook: "Linguistic relativity = your language shapes your world.",
    arabicSupport: "النسبية اللغوية",
  },
  {
    id: 67,
    concept: "Kinship Terms",
    chapter: "Sociolinguistics",
    chapterId: 9,
    whatIsIt: "Words used to describe family relationships — and the way different languages classify relatives reveals cultural priorities.",
    whyShouldICare: "Arabic has extremely precise kinship terms that English lacks. This affects how family is conceptualised and talked about.",
    nibrasMoment: "In English: 'uncle'\nIn Arabic: ammo, khal, 3ammo, khali — all different.\n\nIn English: 'cousin'\nIn Arabic: ibn 3amm, ibn khal, bint 3amm, bint khal — all specific.\n\nArabic encodes family precision that English does not.",
    memoryHook: "Kinship terms = family vocabulary as cultural mirror.",
    arabicSupport: "مصطلحات القرابة",
  },
  {
    id: 68,
    concept: "Classifiers",
    chapter: "Sociolinguistics",
    chapterId: 9,
    whatIsIt: "Grammatical systems in some languages where nouns are grouped into categories and require specific counting words.",
    whyShouldICare: "Classifiers show that different languages categorise the world differently. English has a few (like 'a flock of birds'), but other languages use them constantly.",
    nibrasMoment: "In Arabic, we use classifiers subtly:\n«قطيع» (flock) for sheep\n«صف» (row) for students\n\nSome languages like Mandarin and Thai require a classifier for EVERY counted noun.\n\nIt is a window into how different minds organise the world.",
    memoryHook: "Classifiers = counting categories that reveal cultural thinking.",
    arabicSupport: "المصنفات اللغوية",
  },
  {
    id: 69,
    concept: "Gendered Speech",
    chapter: "Sociolinguistics",
    chapterId: 9,
    whatIsIt: "Differences in how men and women speak, including vocabulary choices, intonation patterns, and conversational styles.",
    whyShouldICare: "Gendered speech patterns affect how you are perceived. Being aware of them helps you communicate more effectively in different social contexts.",
    nibrasMoment: "Research shows women tend to use more hedge words:\n\"I think maybe we could possibly…\"\n\nWhile men tend to use more direct forms:\n\"We should do this.\"\n\nThese are tendencies, not rules — but they affect perception.",
    memoryHook: "Gendered speech = how gender shapes language choices.",
    arabicSupport: "الكلام المفند بالجنس",
  },
  // ═══════════════════════════════════════════════════
  // CHAPTER 10: HISTORICAL LINGUISTICS
  // ═══════════════════════════════════════════════════
  {
    id: 70,
    concept: "Language Change",
    chapter: "Historical Linguistics",
    chapterId: 10,
    whatIsIt: "The process by which languages evolve over time — sounds, grammar, vocabulary, and meaning all shift gradually across generations.",
    whyShouldICare: "The English you speak today is very different from Shakespeare's English, and both are different from Old English. Change is the only constant in language.",
    nibrasMoment: "Your grandparents say:\n«هيك» (heik)\n\nYounger Jordanians might say:\n«كده» (keda)\n\nEven within one generation, Arabic is shifting — that is language change in action.",
    memoryHook: "Language change = language's slow evolution.",
    arabicSupport: "تغير اللغة",
  },
  {
    id: 71,
    concept: "Sound Change",
    chapter: "Historical Linguistics",
    chapterId: 10,
    whatIsIt: "How the pronunciation of words shifts over centuries — vowels and consonants gradually transform in predictable patterns.",
    whyShouldICare: "Sound change explains why English spelling often does not match pronunciation — the spelling reflects older pronunciation that no longer exists.",
    nibrasMoment: "Why is 'knight' pronounced 'nite'?\n\nBecause hundreds of years ago, the 'k' and 'gh' were actually pronounced.\n\nSound change made them silent — but spelling kept the old forms.",
    memoryHook: "Sound change = pronunciation evolving over time.",
    arabicSupport: "التغير الصوتي",
  },
  {
    id: 72,
    concept: "Borrowing",
    chapter: "Historical Linguistics",
    chapterId: 10,
    whatIsIt: "When a language takes words from another language and makes them its own — the most common source of new vocabulary in any language.",
    whyShouldICare: "English has borrowed from over 350 languages. Arabic itself has contributed many words. Understanding borrowing reveals cultural connections.",
    nibrasMoment: "English words from Arabic:\n— algebra (الجبر)\n— algorithm (الخوارزمي)\n— coffee (قهوة)\n— magazine (مخزن)\n\nThese are not just loanwords — they are cultural bridges.",
    memoryHook: "Borrowing = language's cultural exchange program.",
    arabicSupport: "الاستعارة اللغوية",
  },
  {
    id: 73,
    concept: "Cognate",
    chapter: "Historical Linguistics",
    chapterId: 10,
    whatIsIt: "Words in different languages that share a common ancestral origin — they look and sound similar because they evolved from the same ancient word.",
    whyShouldICare: "Recognising cognates gives you instant vocabulary in related languages. Arabic and English share more cognates than most people realise.",
    nibrasMoment: "Arabic «مدينة» (madina) and English 'medicine' share an ancient Semitic root related to healing.\n\nNot exact cognates, but deeply connected — showing how languages are more related than we think.",
    memoryHook: "Cognate = language cousins sharing family resemblance.",
    arabicSupport: "كلمات مشتركة الأصل",
  },
  {
    id: 74,
    concept: "Reconstruction",
    chapter: "Historical Linguistics",
    chapterId: 10,
    whatIsIt: "The method linguists use to rebuild ancient, unrecorded languages by comparing their modern descendants and tracing patterns backwards.",
    whyShouldICare: "Reconstruction lets us understand languages that were never written down. It is like linguistic detective work.",
    nibrasMoment: "Proto-Arabic was spoken thousands of years ago but never written.\n\nBy comparing modern Arabic dialects and Semitic languages, linguists reconstruct what it might have sounded like.\n\nIt is language archaeology.",
    memoryHook: "Reconstruction = linguistic time travel.",
    arabicSupport: "إعادة البناء اللغوي",
  },
  {
    id: 75,
    concept: "Proto-language",
    chapter: "Historical Linguistics",
    chapterId: 10,
    whatIsIt: "The hypothetical ancestor language from which a family of related languages descended — never directly recorded but reconstructed by linguists.",
    whyShouldICare: "Proto-languages reveal that most of the world's languages are connected through ancient families. Arabic, Hebrew, and Amharic all come from Proto-Semitic.",
    nibrasMoment: "Proto-Semitic was spoken around 4,000 BCE.\n\nFrom it came Arabic, Hebrew, Aramaic, Amharic, and more.\n\nA Jordanian student, a Lebanese student, and an Ethiopian student all speak languages that share one ancient mother tongue.",
    memoryHook: "Proto-language = the ancient mother of a language family.",
    arabicSupport: "اللغة الأم",
  },
];

export const chapters = [
  { id: 1, name: "Phonetics & Phonology", icon: "🔊", range: [1, 9] },
  { id: 2, name: "Morphology", icon: "🧩", range: [10, 17] },
  { id: 3, name: "Syntax", icon: "🏗️", range: [18, 23] },
  { id: 4, name: "Semantics", icon: "💡", range: [24, 33] },
  { id: 5, name: "Pragmatics", icon: "🎯", range: [34, 41] },
  { id: 6, name: "Discourse Analysis", icon: "🔗", range: [42, 47] },
  { id: 7, name: "Neurolinguistics", icon: "🧠", range: [48, 52] },
  { id: 8, name: "Language Acquisition", icon: "👶", range: [53, 57] },
  { id: 9, name: "Sociolinguistics", icon: "🌍", range: [58, 69] },
  { id: 10, name: "Historical Linguistics", icon: "📜", range: [70, 75] },
];
